LSR.web/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using LSR.Common;
using LSR.Models;

namespace LSR.Controllers
{
    public class MusicController : Controller
    {
        private LSREntities db = new LSREntities();

        public string CreateSessionWithCookie()
        {
            string userId = CreateSessionWithCookie_NonRedirect();
            if (string.IsNullOrEmpty(userId))
            {
                Response.Write("<script>alert('您还没有登录哦，请您登录哦！！(๑•̀ㅂ•́)و✧====>>(ノ｀Д´)ノへ┻┻');window.location.href='/LSR/User/Login'</script>");
                return null;

            }            
            else return userId;
        }
        public string CreateSessionWithCookie_NonRedirect()
        {
            if (Session["UserId"] == null)
            {
                var cookie = Request.Cookies.Get($"UserInfo");
                if (cookie == null)
                {
                    return null;
                }
                var UserId = cookie.Values["UserId"];
                var Pwd = cookie.Values["Password"];
                var user = db.User_InfoSet.Find(Convert.ToInt64(UserId));
                if (user == null || user.PassWord != Pwd)
                {
                    return null;
                }
                else
                {
                    Session["UserId"] = user.UserId;
                    Session["UserName"] = user.UserName;

                    if (user.Image != null && user.Image != "")
                    {
                        Session["UserAvatar_cs"] = System.Configuration.ConfigurationManager.AppSettings["AvatarFolder_cs"] + "/" + user.Image;
                        Session["UserAvatar_js"] = System.Configuration.ConfigurationManager.AppSettings["AvatarFolder_js"] + "/" + user.Image;
                        Session["AvatarBase64"] = ImgProcession.ImageToBase64(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["AvatarFolder_cs"] + "\\" + user.Image));
                    }


                    else
                    {
                        Session["UserAvatar_cs"] = System.Configuration.ConfigurationManager.AppSettings["AvatarFolder_cs"] + "/" + System.Configuration.ConfigurationManager.AppSettings["DefaultAvatar"];
                        Session["AvatarBase64"] = ImgProcession.ImageToBase64(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["AvatarFolder_cs"] + "\\" + System.Configuration.ConfigurationManager.AppSettings["DefaultAvatar"]));
                        Session["UserAvatar_js"] = System.Configuration.ConfigurationManager.AppSettings["AvatarFolder_js"] + "/" + System.Configuration.ConfigurationManager.AppSettings["DefaultAvatar"];
                    }
                    return Session["UserId"].ToString();
                }
            }
            else return Session["UserId"].ToString();
        }

        // GET: Music
        public ActionResult Index(bool? Logout)
        {
            if (Logout == true)
            {

                Session.RemoveAll();
                Response.Cookies.Remove("UserInfo");
                return View();
            }
            else
            {
                _ = CreateSessionWithCookie_NonRedirect();
                return View();
            }                   
        }

        // GET: Music/Create
        public ActionResult Create()
        {
            CreateSessionWithCookie();
            return View();
        }

        // POST: Music/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MusicId,MusicName,Author,AlbumName,MusicDuration,UploadDate,UploaderName,FileSize,MusicFormat")] MusicSet music)
        {
            if (Session["UserId"] == null)
            {
                Response.Write("<script>alert('您还没有登录哦，请您登录哦！！(๑•̀ㅂ•́)و✧====>>(ノ｀Д´)ノへ┻┻');window.location.href='../User/Login'</script>");
                return Content("登录状态已过期");

            }
            if (ModelState.IsValid)
            {
                db.MusicSet.Add(music);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(music);
        }

        // GET: Music/Edit/5
        public ActionResult Edit(long? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicSet music = db.MusicSet.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Music/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MusicId,MusicName,Author,AlbumName,MusicDuration,UploadDate,User,FileSize,MusicFormat")] MusicSet music)
        {
            if (ModelState.IsValid)
            {
                db.Entry(music).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(music);
        }

        // GET: Music/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicSet music = db.MusicSet.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        // POST: Music/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            MusicSet music = db.MusicSet.Find(id);
            db.MusicSet.Remove(music);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //public ActionResult Play()
        //{
        //    return View();
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]

        public ActionResult Play()
        {
            CreateSessionWithCookie();
            if (Session["UserId"] == null)
            {
                Response.Write("<script>alert('走开太久咯，请您新登录哦！！(๑•̀ㅂ•́)و✧====>>(ノ｀Д´)ノへ┻┻');window.location.href='../../User/Login'</script>");
                return Content("登录状态已过期");
            }
            //if(Request.Params["MusicId"]==null) return RedirectToAction("Search", "Music", new { s = "李宇春" });
            var userId = Session["UserId"].ToString();
            var musicIdOn = Request["MusicIdOn"];
            var musicIdOff = Request["MusicIdOff"];
            if (musicIdOn != null && musicIdOn != "") {
                var PlayListCookie = Request.Cookies.Get("PlayListCookie-u" + userId);
                if (PlayListCookie == null)
                {
                    PlayListCookie = new HttpCookie("PlayListCookie-u" + userId);


                }
                var PlayList = PlayListCookie.Values["PlayList"].ToString();

                //播放列表是一个字符串类似于1,2,3,4,5,6
                //播放列表中没有内容
                if (PlayList == null || PlayList == "") PlayList = musicIdOn;
                //这首歌存在于播放列表，而且这首歌在播放列表的中间或尾巴
                else if (PlayList.Contains("," + musicIdOn)) PlayList = PlayList.Replace("," + musicIdOn, "") + "," + musicIdOn;
                //这首歌还没有存在于播放列表或者这首歌在播放列表的头头上
                else PlayList = PlayList.Replace(musicIdOn + ",", "") + "," + musicIdOn;

                PlayListCookie.Values["PlayList"] = PlayList;
                PlayListCookie.Values["UserId"] = userId;
                PlayListCookie.Expires = DateTime.Now.AddMonths(1);
                Response.Cookies.Add(PlayListCookie);

                return null;
            }
            else if (musicIdOff != null && musicIdOff != "")
            {
                var PlayListCookie = Request.Cookies.Get("PlayListCookie-u" + userId);
                if (PlayListCookie == null)
                {
                    PlayListCookie = new HttpCookie("PlayListCookie-u" + userId);


                }
                var PlayList = PlayListCookie.Values["PlayList"].ToString();

                //播放列表是一个字符串类似于1,2,3,4,5,6
                //播放列表中没有内容
                if (PlayList == null || PlayList == "") PlayList = musicIdOff;
                //这首歌存在于播放列表，而且这首歌在播放列表的中间或尾巴
                else if (PlayList.Contains("," + musicIdOff)) PlayList = PlayList.Replace("," + musicIdOff, "") + "," + musicIdOff;
                //这首歌还没有存在于播放列表或者这首歌在播放列表的头头上
                else PlayList = PlayList.Replace(musicIdOff + ",", "") + "," + musicIdOff;

                PlayListCookie.Values["PlayList"] = PlayList;
                PlayListCookie.Values["UserId"] = userId;
                PlayListCookie.Expires = DateTime.Now.AddMonths(1);
                Response.Cookies.Add(PlayListCookie);

                var PlayListMusicNames = PlayList.Split(',');
                List<MusicSet> MusicList = new List<MusicSet>();
                foreach (var item in PlayListMusicNames)
                {
                    var music = db.MusicSet.Find(Convert.ToInt64(item));
                    MusicList.Add(music);
                }
                return View(MusicList);
            }

            //ViewBag.MusicName =music.MusicName;
            //ViewBag.Author = music.ArtistSet.Name;
            //ViewBag.Album = music.AlbumSet.Name;

LSR.web/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LSR.Models;
using LSR.Common;
using System.IO;

namespace LSR.Controllers
{
    public class PlayerController : Controller
    {
        LSREntities db = new LSREntities();
        // GET: Player
        
        public ActionResult LyricsPage(long? s)
        {
            if (s == null) return null;
            var fileName = db.MusicSet.Find(s).MusicLyrics;
            fileName = Server.MapPath($"{System.Configuration.ConfigurationManager.AppSettings["MusicLyricsFolder"]}\\{fileName}");
            StreamReader LyricsSR = new StreamReader(fileName, System.Text.Encoding.UTF8);
            var LyricsText = LyricsSR.ReadToEnd().Split('\n').ToList();
            List<string> LyricsList = new List<string>();
            foreach (var item in LyricsText) LyricsList.Add(item.Replace("\n", "").Replace(" ", "").Replace("\t", "").Replace("\r", ""));
            LyricsSR.Close();
            return PartialView(LyricsList);
        }
        
    }
}

LSR.web/Views/Music/AlbumCard.cshtml
@model LSR.Models.AlbumSet
<style>
    .littleCard > *, .littleCard {
        border: 0;
    }

    .littleCard {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

        .littleCard > a > img {
            width: 96px;
            aspect-ratio: 1/1;
            
        }

    .mr {
        margin-right: 20px;
    }

    .Artist-Info {
        display: inline-block;
        margin-left: 10px;
    }

    h2 {
        display: inline;
        margin-right: 10px;
        font-size: 120%;
        font-weight: 500;
    }

    .BtnDiv {
        margin-top: 10px;
    }
</style>
<div class="littleCard">
    <a href="../Music/Main?Type=3&s=@Model.AlbumId" class=""><img src="@Model.Image"></a>
    <div class="Artist-Info">
        <div>
            <h2>
                <a href="../Music/Main?Type=3&s=@Model.AlbumId" class="">@Model.Name</a>
            </h2>
            
        </div>
        <div class="BtnDiv">
            <button type="button" class="btn btn-primary">播放全部</button>
        </div>
    </div>
</div>
<script type="text/javascript">
    function playAllBtn() {
        if ($.cookie('PlayerWindowName') == null)
            PlayerPage = window.open('/LSR/Player/Main?s=' + e + '&Type=' + t, 'PlayerPage');
        else {
            PlayerPage = window.open('', 'PlayerPage')
            PlayerPage.PlayOneNow(e);
            PlayerPage.focus();
        }
        $.ajax({
            url: '/LSR/Music/PlayNow',
            data: 's=@Model.AlbumId?Type=2',
            type: 'post',
            success: data => {
                eval(data);
            },
            error: data => {
                DoTipBox('error', '播放失败！')
            }
        });
    }
</script>

LSR.web/Views/Music/DisplaySheet.cshtml
@model IEnumerable<LSR.Models.MusicSheetSet>

@switch (ViewBag.type)
{
    case 1:
        {
            <li>
                @Ajax.ActionLink("下一首播放", "AddToPlayList", "Music",
            new { s = ViewBag.theMusicId, Type = 1 },
            new AjaxOptions { OnSuccess = "DoTipBox('success','添加成功')", OnFailure = "DoTipBox('error','添加失败')" },
            new { @class = "dropdown-item " })
            </li>
            <li>
                @Ajax.ActionLink("我喜欢", "AddLike", "Music",
            new { s = ViewBag.theMusicId, Type = 1 },
            new AjaxOptions { OnSuccess = $"Add_Like_Suc_Func({ViewBag.theMusicId})", OnFailure = "DoTipBox('error','添加失败')" },
            new { @class = $"dropdown-item ",id=$"MyLike_{ViewBag.theMusicId}" })
            </li>
            foreach (var theSheet in Model)
            {


                <li>
                    @Ajax.ActionLink(theSheet.Name, "AddToSheet", "Music",
                    new { s = ViewBag.theMusicId, sheetId = theSheet.MusicSheetId, Type = 1 },
                    new AjaxOptions { OnSuccess = $"addLikeSuc({ViewBag.theMusicId})", OnFailure = "DoTipBox('error','添加失败')" },
                    new { @class = "dropdown-item ", id = "MusicSheet_" + theSheet.MusicSheetId })

                </li>
            }
            <li><button type="button" class="dropdown-item" onclick="CreateSheetWindow()"><i class="bi bi-plus-square"></i>  添加一个新的歌单</button></li>
            
            <script type="text/javascript">
    $(() => {
        @foreach(var item in Model)
    {
        var musicId = Convert.ToInt64(ViewBag.theMusicId);
        var log = item.Music_MusicSheet_rel.FirstOrDefault(m => m.MusicId == musicId);

        if (log != null)
        {
                    <text>
        $('#MusicSheet_@item.MusicSheetId').addClass('disabled');
                    </text>
            }

    }
        if (@ViewBag.IsLiking) {
            $('#MyLike_@ViewBag.theMusicId').toggleClass('disabled');
        }
})
    
    
    function CreateSheetWindow() {
        const tzAlert = new TzAlert({
            center: true, // 内容居中
                          // 实例化完成直接显示
            confirm: {
                use: true,
                text: '确认',
                textColor: '#fff',
                bgColor: '#0d6efd',
                radius: '6px',
                border: '1px solid #0d6efd',
                shadow: '0px 1px 10px rgba(19, 17, 85, 0.4)',
                padding: '6px 15px',
            },
            cancel: {
                use: true,
                text: '取消',
                textColor: '#333',
                bgColor: '#fff',
                border: '1px solid #0d6efd',
                radius: '6px',
                shadow: '0px 1px 3px rgba(19, 17, 85, 0.4)',
                padding: '6px 15px',
            },

            title: {
                html: '添加一个新的歌单',
                color: '#0d6efd',
                fontSize: '18px',
            },
            maskClose: true,
            copy: {
                use: false
            },
            mask: {
                use: true,
                background: 'rgba(0,0,0,.6)'
            },
            tips: {
                html: '我的新歌单'
            },
            content: {
                html: '<input id="InputSheet" type="text" style="min-width: 300px;min-height: 40px;border-radius: 6px;border: 1px solid #3eacff;color: #6a6f77;-web-kit-appearance: none;-moz-appearance: none;display: block;outline: 0;padding: 0 1em;text-decoration: none;width: 80%;"id="SheetName" name="SheetName" required="required" placeholder="给新歌单起个名字吧">'
            },
            onEvents:function(e) {
                if (e.cancel == true) e.ctx.close();
                if (e.confirm == true) {
                    confirmBtn(e);
                }

            }

        });
        tzAlert.open();

    }

    function confirmBtn(e) {
        var inputSheet = $('#InputSheet');
        var sheetName = inputSheet.val();
        console.log(sheetName);
        if (sheetName == null || sheetName == "") {

            /*$('#requireText').fadeIn(); alert("输入歌单名！");*/
            new TipBox({ type: 'error', str: '输入歌单名', setTime: 1500 });
            e.ctx.close();
            $('.alert-wrap').remove();
            $('.alert-mask').remove();
        }
        else {
            $.ajax({
                url: '../Music/CreateSheet?SheetName=' + sheetName,
                type: 'post',
                data: {},
                contentType: false,
                processData: false,
                success: data => {
                    new TipBox({ type: 'success', str: data, setTime: 1500 });
                    e.ctx.close();
                    $('.alert-wrap').remove();
                    $('.alert-mask').remove();
                },
                error: data => {
                    new TipBox({ type: 'error', str: '歌单已存在', setTime: 1500 });
                    e.ctx.close();
                    $('.alert-wrap').remove();
                    $('.alert-mask').remove();
                }
            });

        }
    }
       /* inputSheet.val("");*/

            </script>
            break;
        }
    case 2:
        {            
            <li>
                @Ajax.ActionLink("我喜欢", "AddLike", "Music",
            new { s = ViewBag.theAlbumId, Type = 2 },
            new AjaxOptions { OnSuccess = "DoTipBox('success','添加成功')", OnFailure = "DoTipBox('error','添加失败')" },
            new { @class = "dropdown-item " })<hr />
            </li>
            foreach (var theSheet in Model)
            {


                <li>
                    @Ajax.ActionLink(theSheet.Name, "AddToSheet", "Music",
                    new { s = ViewBag.theAlbumId, sheetId = theSheet.MusicSheetId, Type = 2 },
                    new AjaxOptions { OnSuccess = "DoTipBox('success','添加成功')", OnFailure = "DoTipBox('error','添加失败')" },
                    new { @class = "dropdown-item ", id = "MusicSheet_" + theSheet.MusicSheetId })

                </li>
            }
            <li><button type="button" class="dropdown-item" onclick="CreateSheetWindow()"><i class="bi bi-plus-square"></i>  添加一个新的歌单</button></li>
            <link href="~/css/alert.min.css" rel="stylesheet" />
            <link href="~/css/alert.ani.min.css" rel="stylesheet" />
            <script src="~/js/zepto.min.js"></script>
            <script src="~/js/TipBox.js"></script>
            <script src="~/js/alert.min.js"></script>
            <script type="text/javascript">
    
    function DoTipBox(t, s) {
    new TipBox({ type: t, str: s, setTime: 1500 });
    }

    function CreateSheetWindow() {
        const tzAlert = new TzAlert({
            center: true, // 内容居中
                          // 实例化完成直接显示
            confirm: {
                use: true,
                text: '确认',
                textColor: '#fff',
                bgColor: '#0d6efd',
                radius: '6px',
                border: '1px solid #0d6efd',
                shadow: '0px 1px 10px rgba(19, 17, 85, 0.4)',
                padding: '6px 15px',
            },
            cancel: {
                use: true,
                text: '取消',
                textColor: '#333',
                bgColor: '#fff',
                border: '1px solid #0d6efd',
                radius: '6px',
                shadow: '0px 1px 3px rgba(19, 17, 85, 0.4)',
                padding: '6px 15px',
            },

            title: {
                html: '添加一个新的歌单',
                color: '#0d6efd',
                fontSize: '18px',
            },
            maskClose: true,
            copy: {
                use: false
            },
            mask: {
                use: true,
                background: 'rgba(0,0,0,.6)'
            },
            tips: {
                html: '我的新歌单'
            },
            content: {
                html: '<input id="InputSheet" type="text" style="min-width: 300px;min-height: 40px;border-radius: 6px;border: 1px solid #3eacff;color: #6a6f77;-web-kit-appearance: none;-moz-appearance: none;display: block;outline: 0;padding: 0 1em;text-decoration: none;width: 80%;"id="SheetName" name="SheetName" required="required" placeholder="给新歌单起个名字吧">'
            },
            onEvents:function(e) {
                if (e.cancel == true) e.ctx.close();
                if (e.confirm == true) {
                    confirmBtn(e);
                }

            }

        });
        tzAlert.open();

    }

    function confirmBtn(e) {
        var inputSheet = $('#InputSheet');
        var sheetName = inputSheet.val();
        console.log(sheetName);
        if (sheetName == null || sheetName == "") {

            /*$('#requireText').fadeIn(); alert("输入歌单名！");*/
            new TipBox({ type: 'error', str: '输入歌单名', setTime: 1500 });
            e.ctx.close();
            $('.alert-wrap').remove();
            $('.alert-mask').remove();
        }
        else {
            $.ajax({
                url: '../Music/CreateSheet?SheetName=' + sheetName,
                type: 'post',
                data: {},
                contentType: false,
                processData: false,
                success: data => {
                    new TipBox({ type: 'success', str: data, setTime: 1500 });
                    e.ctx.close();
                    $('.alert-wrap').remove();
                    $('.alert-mask').remove();
                },
                error: data => {
                    new TipBox({ type: 'error', str: '歌单已存在', setTime: 1500 });
                    e.ctx.close();
                    $('.alert-wrap').remove();
                    $('.alert-mask').remove();
                }
            });

        }
    }
       /* inputSheet.val("");*/

            </script>
            break;
        }

}

LSR.web/Views/Music/Library.cshtml
@model IEnumerable<LSR.Models.MusicSet>

@{
    ViewBag.Title = "Library";
    Layout = "~/Views/Shared/Player_Layout.cshtml";
}
<style>
    .list-group {
        width: auto;
        max-width: 720px;
        margin: 1px auto;
    }

    .opacity-50 {
        opacity: .5;
    }

    .opacity-75 {
        opacity: .75;
    }
    ul, ol {
        list-style: none;
    }
    .chose {
        padding-top: 20px;
    }

        .chose .box {
            width: 100%;
            display: flex;
            align-items: center;
            margin-bottom: 15px;
        }

            .chose .box ul {
                display: flex;
                flex-wrap: wrap;
                /*width: 90%;*/
                margin: 0;
            }

                .chose .box ul li {
                    color: #161616;
                    font-size: 14px;
                    cursor: pointer;
                    border: 1px solid #afafaf;
                    padding: 7px 14px;
                    border: 1px solid #afafaf;
                    border-right: none;
                }

                    .chose .box ul li:nth-of-type(1) {
                        margin-right: 10px;
                        border-radius: 4px;
                        border-right: 1px solid #afafaf;
                    }

                    .chose .box ul li:nth-of-type(2) {
                        border-radius: 4px 0 0 4px;
                    }

                    .chose .box ul li:nth-last-of-type(1) {
                        border-radius: 0 4px 4px 0;
                        border-right: 1px solid #afafaf;
                    }

                    .chose .box ul li:hover {
                        background: #fb729930;
                        color: #fb7299;
                    }

                    .chose .box ul li.act {
                        color: #fb7299;
                        border-color: #fb7299;
                        border-right: none;
                        background-color: #fb729930;
                        font-weight: 700;
                    }

                    .chose .box ul li:nth-of-type(1).act {
                        border-right: 1px solid #fb7299;
                    }

                    .chose .box ul li:nth-last-of-type(1).act {
                        border-right: 1px solid #fb7299;
                    }

                    .chose .box ul li.act2 {
                        border-left: 1px solid #fb7299;
                    }

                    .chose .box ul li:nth-of-type(2).act2 {
                        border-left: 1px solid #afafaf;
                    } 
</style>
<input type="text" id="test"/>
<button onclick="sss($('#test').val())">试试看</button>
<script type="text/javascript">
    function sss(e) {
        $.ajax({
            url: '/LSR/Music/GetStyles',
            data: {},
        type: 'post',
            success: data => {
                console.log(data);
            },
            error: data => {
                DoTipBox('error', '发生错误了!');
            }
        });
    }
</script>
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                @Ajax.ActionLink("歌手", "SearchLirary", "Music", new {  Type = 1 }, new AjaxOptions { OnComplete = "AriaActive(1)", UpdateTargetId = "cardBody", HttpMethod = "GET", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link active a1", aria_current = "true" })
            </li>
            <li class="nav-item">
                @Ajax.ActionLink("专辑", "SearchLirary", "Music", new { s = Model, Type = 2 }, new AjaxOptions { OnComplete = "AriaActive(2)", UpdateTargetId = "cardBody", HttpMethod = "GET", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link a2" })

            </li>
            
            <li class="nav-item">
                @Ajax.ActionLink("歌单", "SearchLirary", "Music", new { s = Model, Type = 3 }, new AjaxOptions { OnComplete = "AriaActive(4)", UpdateTargetId = "cardBody", HttpMethod = "GET", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link a4" })

            </li>
            <li class="nav-item">
                @Ajax.ActionLink("MV", "SearchLirary", "Music", new { s = Model, Type = 4 }, new AjaxOptions { OnComplete = "AriaActive(3)", UpdateTargetId = "cardBody", HttpMethod = "GET", InsertionMode = InsertionMode.Replace }, new { @class = "nav-link a3" })

            </li>
        </ul>
    </div>

    <div class="card-body" id="cardBody">
        @Html.Action("SearchLibrary", new { Type = 1 })

    </div>
</div>

LSR.web/Views/Music/Play.cshtml
@model LSR.Models.MusicSet
@{
    ViewBag.Title = "Play";
    Layout = "~/Views/Shared/Player_Layout.cshtml";
}
<h1>@Model.MusicName -@Model.ArtistSet.Name</h1>
<link href="~/Content/APlayer.min.css" rel="stylesheet" />

    <div id="player" class="aplayer"></div>
    @Scripts.Render("~/Scripts/APlayer.min.js")

<script language="JavaScript">

        const ap = new APlayer({
            container: document.getElementById('player'),
            mini: false,
            autoplay: false,
            loop: 'all',
            fixed: false,
            mutex: true,
            lrcType: 3,
            audio: {
                    name: '@Model.MusicName',
                    artist: '@Model.ArtistSet.Name',                    
                    url: '@System.Configuration.ConfigurationManager.AppSettings["_MusicFileFolder"]/@Model.MusicFile',
                    cover: '@System.Configuration.ConfigurationManager.AppSettings["_MusicImagesFolder"]/@Model.MusicImage',
                    lrc: '@System.Configuration.ConfigurationManager.AppSettings["_MusicLyricsFolder"]/@Model.MusicLyrics',
                    theme: '#ebd0c2'
            }
        });
</script>
    <div class="text-center">
        @Html.ActionLink("回到音乐清单", "Library", "Music")
    </div>

LSR.web/Views/Music/SearchCardView.cshtml
@model List<Dictionary<string,string>>
<link href="~/css/reset.min.css" rel="stylesheet" />
<link href="~/css/Cards.css" rel="stylesheet" />

            <script type="text/javascript">
                $(() => {
                    $('.card-body').addClass("flex-wrap");
                })
            </script>
            @foreach (var item in Model)
            {            
                Html.RenderPartial("SingleCard", item);
            }
            
       
     

LSR.web/Views/Music/ShowLyrics.cshtml
@model List<string> 
<div class="text-start" style="margin-right:50px;">
@foreach (var item in Model)
{
{<p>@item</p>}
    }
</div>